chroms:
  - chr1
  - chr2
  - chr3
  - chr4
  - chr5
  - chr6
  - chr7
  - chr8
  - chr9
  - chr10
  - chr11
  - chr12
  - chr13
  - chr14
  - chr15
  - chr16
  - chr17
  - chr18
  - chr19
  - chr20
  - chr21
  - chr22
  - chrX
  - chrY

samples:
  - L1_mCherry_M1A
  - L1_mCherry_M2B
  - L1_mCherry_M3C
  - L1_mCherry_M4D
  - L1_mCherry_M5E 

reference:
  /path/to/ref.fa

xtea_dir:
  /path/to/xTea/

tldr_dir:
  /path/to/tldr/

base_dir:
  /path/to/working/dir

somrit_dir:
  /path/to/somrit/

repbase:
  /utils/L1_EF1alpha-mCherry_spliced.fa

centromeres:
  /utils/hg38_centromeres.tsv

telomeres:
  /utils/hg38_telomeres.tsv


# Required for simulation and nested runs

# Assemblies stored in assembly folder should be in subfolder form of "sample_name/assembly/sample_name.[mat|pat].fa"
assembly_folder:
  /path/to/mat/and/pat/assemblies

pbsim_model:
  /path/to/pbsim/model/file

chrom_lengths:
  /utils/GRCh38_chromosome_sizes.tsv
