chroms:
  - chr1
  - chr2
  - chr3
  - chr4
  - chr5
  - chr6
  - chr7
  - chr8
  - chr9
  - chr10
  - chr11
  - chr12
  - chr13
  - chr14
  - chr15
  - chr16
  - chr17
  - chr18
  - chr19
  - chr20
  - chr21
  - chr22
  - chrX
  - chrY

fractions:
  - 0.03*sample_coverage
  - 0.06*sample_coverage
  - 0.09*sample_coverage
  - 0.12*sample_coverage
  - 0.15*sample_coverage
  - 0.18*sample_coverage
  - 0.21*sample_coverage
  - 0.24*sample_coverage
  - 0.27*sample_coverage
  - 0.30*sample_coverage
  - 0.33*sample_coverage

# 3 replicates for Polymorphic, 12 for simulation
replicates:
  - 1
  - 2
  - 3

coverage:
  - sample_coverage

fastq:
  /path/to/input/fastq.gz

reference:
  /path/to/ref.fa

xtea_dir:
  /path/to/xTea/

tldr_dir:
  /path/to/tldr/

base_dir:
  /path/to/working/dir

somrit_dir:
  /path/to/somrit/

repbase:
  /path/to/somrit/repeats.fa

centromeres:
  /utils/hg38_centromeres.tsv

telomeres:
  /utils/hg38_telomeres.tsv

full_sample:
  sample_name

mat_fa:
  /path/to/maternal_assembly.fa

pat_fa:
  /path/to/paternal_assembly.fa

mat_rm:
  /path/to/maternal_repeatmasker.txt

pat_rm:
  /path/to/paternal_repeatmasker.txt

# Required for simulation and nested runs

# Assemblies stored in assembly folder should be in subfolder form of "sample_name/assembly/sample_name.[mat|pat].fa"
assembly_folder:
  /path/to/mat/and/pat/assemblies

pbsim_model:
  /path/to/pbsim/model/file

chrom_lengths:
  /utils/GRCh38_chromosome_sizes.tsv
